top:
  - link: ""
    titles:
      - lang: en
        title: Products
      - lang: hu
        title: Termékek
      - lang: ru
        title: Товары
      - lang: de
        title: Produkte
      - lang: es
        title: Productos
      - lang: fr
        title: Des produits
      - lang: he
        title: מוצרים
      - lang: it
        title: Prodotti
      - lang: ja
        title: 製品
      - lang: pt
        title: Produtos
      - lang: tr
        title: Ürünler
      - lang: zh
        title: 产品
      - lang: ko
        title: 제품
      - lang: ar
        title: منتجات
    subpages:
      - link: urodapter
      - link: urostill
  - subpages:
      - link: ic-bps
      - link: rutis
      - link: post-cancer-treatment
      - link: bladder-cancer
      - link: other-uses-and-indications
    titles:
      - lang: en
        title: Indications
      - lang: ru
        title: Показания
      - lang: hu
        title: Felhasználási területek
      - lang: de
        title: Indikationen
      - lang: ko
        title: 사용처
      - lang: fr
        title: Les indications
      - lang: he
        title: אינדיקציות
      - lang: it
        title: Indicazioni
      - lang: ja
        title: 適応症
      - lang: pt
        title: Indicações
      - lang: es
        title: Indicaciones
      - lang: tr
        title: Belirteçler
      - lang: zh
        title: 适应症
      - lang: ar
        title: دواعي الإستعمال
    link: null
  - link: company
    titles:
      - lang: en
        title: Company
      - lang: hu
        title: UroSystem Zrt.
      - lang: ru
        title: Компания
      - lang: de
        title: Unsere Firma
      - lang: it
        title: UroSystem
      - lang: es
        title: UroSystem
      - lang: pt
        title: UroSystem
      - lang: ja
        title: UroSystem
      - lang: zh
        title: UroSystem
      - lang: ar
        title: شركتنا
      - lang: he
        title: UroSystem
      - lang: ko
        title: 회사
      - lang: tr
        title: UroSystem
      - lang: fr
        title: UroSystem
    subpages:
      - link: company#about
        titles:
          - lang: en
            title: About
          - lang: hu
            title: Rólunk
          - lang: ru
            title: О нас
          - lang: de
            title: Über uns
          - lang: fr
            title: Qui Sommes Nous?
          - lang: it
            title: Chi Siamo?
          - lang: es
            title: Sobre nosotros
          - lang: pt
            title: Sobre Nós
          - lang: zh
            title: 关于我们
          - lang: ja
            title: 会社概要
          - lang: ar
            title: معلومات عنا
          - lang: he
            title: עלינו
          - lang: ko
            title: 회사소개
          - lang: tr
            title: Hakkımızda
      - link: /contact
        titles:
          - lang: en
            title: Contact
          - lang: hu
            title: Kapcsolat
          - lang: ru
            title: Контакт
          - lang: de
            title: Kontakt
          - lang: fr
            title: Contacter
          - lang: it
            title: Contatto
          - lang: es
            title: Contacto
          - lang: pt
            title: Contato
          - lang: ja
            title: 連絡先
          - lang: zh
            title: 关于我们
          - lang: ar
            title: معلومات عنا
          - lang: he
            title: איש קשר
          - lang: ko
            title: 연락처
          - lang: tr
            title: İletişim
      - link: company#partners
        titles:
          - lang: en
            title: Partners
          - lang: hu
            title: Partnerek
          - lang: ru
            title: Партнеры
          - lang: de
            title: Unsere Partner
          - lang: fr
            title: Nos Partenaires
          - lang: it
            title: I Nostri Partner
          - lang: es
            title: Nuestros Compañeros
          - lang: pt
            title: Nossos Parceiros
          - lang: zh
            title: 我們的伙伴
          - lang: ja
            title: 当社のパートナー
          - lang: ar
            title: شركاؤنا
          - lang: he
            title: השותפים שלנו
          - lang: ko
            title: 협력사
          - lang: tr
            title: Ortaklarımız
      - link: company#palyazatok
        titles:
          - lang: hu
            title: Pályázatok
  - link: ""
    titles:
      - lang: en
        title: Events
      - lang: ru
        title: Мероприятия
      - lang: hu
        title: Események
    subpages:
      - link: "#masterclass"
        titles:
          - lang: en
            title: MASTERCLASS in UROLOGY
          - lang: ru
            title: MASTERCLASS in UROLOGY
          - lang: hu
            title: MASTERCLASS in UROLOGY
          - lang: de
            title: MASTERCLASS in UROLOGY
          - lang: ko
            title: MASTERCLASS in UROLOGY
          - lang: fr
            title: MASTERCLASS in UROLOGY
          - lang: he
            title: MASTERCLASS in UROLOGY
          - lang: it
            title: MASTERCLASS in UROLOGY
          - lang: ja
            title: MASTERCLASS in UROLOGY
          - lang: pt
            title: MASTERCLASS in UROLOGY
          - lang: es
            title: MASTERCLASS in UROLOGY
          - lang: tr
            title: MASTERCLASS in UROLOGY
          - lang: zh
            title: MASTERCLASS in UROLOGY
          - lang: ar
            title: MASTERCLASS in UROLOGY
      - link: "#gibs"
        titles:
          - lang: en
            title: GIBS – Urologist's forum on IC/BPS
          - lang: ru
            title: GIBS – Urologist's forum on IC/BPS
          - lang: hu
            title: GIBS – Urologist's forum on IC/BPS
          - lang: de
            title: GIBS – Urologist's forum on IC/BPS
          - lang: ko
            title: GIBS – Urologist's forum on IC/BPS
          - lang: fr
            title: GIBS – Urologist's forum on IC/BPS
          - lang: he
            title: GIBS – Urologist's forum on IC/BPS
          - lang: it
            title: GIBS – Urologist's forum on IC/BPS
          - lang: ja
            title: GIBS – Urologist's forum on IC/BPS
          - lang: pt
            title: GIBS – Urologist's forum on IC/BPS
          - lang: es
            title: GIBS – Urologist's forum on IC/BPS
          - lang: tr
            title: GIBS – Urologist's forum on IC/BPS
          - lang: zh
            title: GIBS – Urologist's forum on IC/BPS
          - lang: ar
            title: GIBS – Urologist's forum on IC/BPS
      - link: "#feppa"
        titles:
          - lang: en
            title: Female Pelvic Pain Association (FEPPA)
          - lang: ru
            title: Female Pelvic Pain Association (FEPPA)
          - lang: hu
            title: Female Pelvic Pain Association (FEPPA)
          - lang: de
            title: Female Pelvic Pain Association (FEPPA)
          - lang: ko
            title: Female Pelvic Pain Association (FEPPA)
          - lang: fr
            title: Female Pelvic Pain Association (FEPPA)
          - lang: he
            title: Female Pelvic Pain Association (FEPPA)
          - lang: it
            title: Female Pelvic Pain Association (FEPPA)
          - lang: ja
            title: Female Pelvic Pain Association (FEPPA)
          - lang: pt
            title: Female Pelvic Pain Association (FEPPA)
          - lang: es
            title: Female Pelvic Pain Association (FEPPA)
          - lang: tr
            title: Female Pelvic Pain Association (FEPPA)
          - lang: zh
            title: Female Pelvic Pain Association (FEPPA)
          - lang: ar
            title: Female Pelvic Pain Association (FEPPA)
  - link: edu
    titles: []
  - link: /shop
    titles: []
